apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-service
  labels:
    app: python-helloworld
  namespace: default
spec:
  selector:
    app: python-helloworld
  type: NodePort
  ports:
  - port: 8081
    targetPort: 6111
    nodePort: 31224
    protocol: TCP
