name: build-docker-image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 
    - shell: bash
      env:
        MY_USER: ${{ secrets.DOCKER_USER }}
      run: |
        echo $MY_USER
        env

    - name: Check env
      run: |
        user=${{secrets.DOCKER_USER}}
        ps=${{secrets.DOCKER_CREDENTIAL}}
        echo user: $user, ps: $ps,you have it
 
    - name: Login to DockerHub
      uses: docker/login-action@v1     
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_CREDENTIAL }}
    
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platform: linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USER}}/python-helloworld:latest
