name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  strategy:
    matrix:
    python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
  steps:
  - uses: actions/checkout@v2
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
  - nanme: Install dependencies
    run: |
      python -m pip install install --upgrade pip
      if [ -f requirements.txt ]; then pip -r requirements.txt; fi
  - name: Test with pytest
    run: |
      pytest
